### ISSUE TITLE
IQ-TREE2 version used?

### ISSUE THREAD

**Issue by claudia-c-weber** [cassiusma/satute#1]
Hi, Arndt pointed me towards your poster at SMBE last week, and the method looks interesting. I have a tree with some very long branches and would like to gauge whether the parameter estimates are likely to be problematic. Unfortunately, I think the output files from the version of IQ-TREE2 that I used may not work with the parsing code.

I found that patching `-mfreq` into `modelAndFrequency` was necessary to get the script to successfully run IQ-TREE version 2.1.3 on the subsequences/clades. When `if multiplicity == 1` the variable M is undefined and causes an error. The string "Rate parameter R:" also doesn't appear in the *.iqtree files I get from amino acid alignments.

Could you confirm which version of IQ-TREE2 you are using?

Thanks!

**Comment by cassiusma** [comment]
Dear Claudia:

Thanks a lot for the input, it is very useful.

The IQ-TREE version we are using is the COVID edition, but this is not the
reason why parsing has not worked.

Rather it must be the fact that aminoacid have been rarely tested and we
did not consider all the casuistic. Indeed the Rate parameter R is the
cornerstone of all this error. It is missing in the output files because
IQ-TREE assumes one of those R matrices estimated from historical data,
without optimizing it.

Could you send me a sample input file? Not necessarily the one you are
using, but the command line plus a similar input file. Then I should be
able to fix it.

Best!
Cassius

**Comment by claudia-c-weber** [comment]
Hi Cassius, thanks for the quick reply!

I realised after I posted the issue that the parser was expecting to find the parameter estimates in the output, which obviously aren't there for empirical models.

I've attached two examples, a codon alignment, and a protein alignment (they're not the ones I previously used, since I pulled out some species with annotations that aren't final, but they show similar behaviour).

`python ../main.py -s ${PWD}/OG0003824.codon.fna -iq /software/iqtree-2.2.2.6-Linux/bin/iqtree2` 

returns the following:

> Here comes the  1 'th fastest evolving region: 
> Order    delta   c_s    Branch status  T2T status      Branch                                                                                             
>      1  0.0847  0.1075  Saturated      SatuT2T        Node1*-Node2*                                                                                       
>      2  0.1087  0.1354  Saturated      SatuT2T        Node2*-Node3*                                                                                       
>      3  0.1370  0.1413  Saturated      SatuT2T        Node2*-Node6*                                                                                       
> Traceback (most recent call last):
>   File "../main.py", line 1332, in <module>
>     saturationTest(pathDATA, pathIQTREE, dimension, numberRates, str(numberRates-i), 2.33, 1, 0.01, not upperestimate)
>   File "../main.py", line 1252, in saturationTest
>     if c_s>delta or M < c_sTwoSequence*c_sTwoSequence:
> UnboundLocalError: local variable 'M' referenced before assignment

For the amino acid alignment:

`python ../main.py -s ${PWD}/OG0000197.aa.fa.txt -iq /software/iqtree-2.2.2.6-Linux/bin/iqtree2 -d 20`

> Here comes the  1 'th fastest evolving region: 
> Traceback (most recent call last):
>   File "../main.py", line 1332, in <module>
>     saturationTest(pathDATA, pathIQTREE, dimension, numberRates, str(numberRates-i), 2.33, 1, 0.01, not upperestimate)
>   File "../main.py", line 1054, in saturationTest
>     state_frequencies_vect =  rate_and_frequenciesALTERNATIVE(pathDATA,number_rates, dimension)
>   File "../main.py", line 871, in rate_and_frequenciesALTERNATIVE
>     modelFinal += separated[0]
> IndexError: list index out of range

This is the case where the string isn't found, and the selected model's frequencies are also simply given as "(model)" in the output.

I hope these are useful. I would also be interested in testing some codon models.

Claudia

[OG0003824.codon.fna.txt](https://github.com/cassiusma/satute/files/12250539/OG0003824.codon.fna.txt)
[OG0000197.aa.fa.txt](https://github.com/cassiusma/satute/files/12250649/OG0000197.aa.fa.txt)

**Comment by cassiusma** [comment]
Very well Claudia,

I will come back to you when I solve the issue. Currently we are updating
the branch to make the code much more sophisticated, so it may be easier to
send you the output. I will keep you updated.

Best,
Cassius
